import React from 'react'
import {
    Container,
    CssBaseline,
    AppBar,
    Typography,
    Grid,
  } from "@mui/material";
const Register = () => {
  return (
    <>
    <Grid container spacing={2}>

      <Grid item xs={6}>
        <Typography variant="h4" gutterBottom>
        Welcome the AI Application
        </Typography>
        <Typography variant="p" gutterBottom>
        Here you can get code by generated by AI. It solve all of your Problems  
        </Typography>
      </Grid>

      <Grid item xs={6}>
        <Typography variant="h1" gutterBottom>
          Hello, World#2
        </Typography>
      </Grid>

    </Grid>
  </>
  )
}

export default Register
